# Generated by Django 4.2.7 on 2023-12-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_cost',
        ),
    ]
