# Generated by Django 4.2.7 on 2023-12-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.ManyToManyField(related_name='orders', to='app.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='items', to='app.item'),
        ),
    ]
